name: aoc2022_day02
description: Advent of Code 2022 puzzle solutions in Dart.
version: 1.0.0
homepage: https://github.com/wiremoons/AdventOfCode2022

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
